version: '3.8'
services:
  # cliq-dev:
  #   build:
  #     context: .
  #     dockerfile: src/Cliq.Server/Dockerfile.dev
  #   ports:
  #     - "7188:7188"  # HTTPS
  #     - "5188:5188"  # HTTP
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:7188;http://+:5188
  #   container_name: cliq-dev
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cliq_database
      POSTGRES_USER: cliq_api_user
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: bc27bedf-a383-40eb-8793-029e36dae2b7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: